from __future__ import annotations

import logging
from pathlib import Path

import faiss
import streamlit as st
from prepare_dataset import ensure_data_ready
from sentence_transformers import SentenceTransformer

DATA_PATH = Path("output.txt")
MODEL_NAME = "all-MiniLM-L6-v2"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("semantic_search_app")

st.set_page_config(page_title="Semantic Search FAISS", page_icon="🔎", layout="centered")


@st.cache_resource
def load_model() -> SentenceTransformer:
    logger.info("Loading model: %s", MODEL_NAME)
    return SentenceTransformer(MODEL_NAME)


@st.cache_data
def load_docs(data_file: str, mtime: float) -> list[str]:
    del mtime  # used only for Streamlit cache invalidation
    path = Path(data_file)
    docs = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    logger.info("Loaded %d documents from %s", len(docs), path)
    return docs


@st.cache_resource
def build_index(docs: tuple[str, ...]):
    model = load_model()
    logger.info("Building FAISS index for %d documents", len(docs))

    embeddings = model.encode(list(docs)).astype("float32")
    faiss.normalize_L2(embeddings)

    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)
    return index


def main() -> None:
    st.title("🔎 Semantic Search with FAISS")
    st.write("Semantic search over requirements from `output.txt`.")

    try:
        if not DATA_PATH.exists():
            with st.spinner("Preparing dataset: downloading and transforming source file..."):
                ensure_data_ready()
    except Exception:
        logger.exception("Failed to prepare dataset")
        st.error("Failed to prepare dataset.")
        st.stop()

    docs = load_docs(str(DATA_PATH), DATA_PATH.stat().st_mtime)
    if not docs:
        st.error("File `output.txt` is empty.")
        logger.error("Data file is empty: %s", DATA_PATH)
        st.stop()

    index = build_index(tuple(docs))
    model = load_model()

    st.caption(f"Documents in index: {len(docs)}")

    query = st.text_input("Search", placeholder="e.g.: refresh display every 60 seconds")
    max_k = min(20, len(docs))
    top_k = st.slider("Top results", min_value=1, max_value=max_k, value=min(5, max_k))

    if not query.strip():
        st.info("Enter a query in the field above.")
    else:
        query_embedding = model.encode([query]).astype("float32")
        faiss.normalize_L2(query_embedding)
        scores, indices = index.search(query_embedding, top_k)

        st.subheader("Results")
        for rank, (score, idx) in enumerate(zip(scores[0], indices[0]), start=1):
            st.markdown(f"**{rank}.** {docs[idx]}")
            st.caption(f"score = {score:.4f}")

    st.markdown("---")
    st.caption("Privacy notice: This application does not collect or store personal data or usage analytics. User inputs are processed only to generate results and are not retained. Standard technical logs may be generated by the Streamlit hosting platform.")


if __name__ == "__main__":
    main()
